name = "luddatumbazo"
pages_build_output_dir = "public"
compatibility_date = "2023-12-01"


################################################################################
# B I N D I N G S
################################################################################

# DEVELOPMENT NOTE:
#
# When using these bindings for local development, problems will arise due to
# the fact that the pages site and the worker site run in separate instances
# of MiniFlare, which means they each have their own local versions of the
# local storage for both bindings.
#
# You want to tie them together by doing an "ln -s" to symlink the "d1" and "r2"
# folders of "backend/.wrangler/state/v3" into the similarly named version on
# the client.
#
# If you don't, you will be confused when the frontend functions don't see the
# same data as the back end does.

# Bind our database; the name and ID come from the D1 page and are visible when
# you create DB or go back to look at one.
[[d1_databases]]
binding = "DB"
database_name = "luddatumbazo"
database_id = "8b684b74-2299-4276-a0b2-f6f6d3a65526"

# Bind our data bucket; the name is specified by you when you create the bucket
# initially.
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "luddatumbazo-assets"


################################################################################
# G E N E R A L
################################################################################

[vars]

# The values here are set when this is actively deployed by CloudFlare as a
# result of pushing a new commit to the repository.
#
# They control what the rollup script that is used to deploy see as far as the
# environment is converned, but they are not used at all locally.
BUILD_TYPE = "production"
GAME_API_ROOT_URI = "https://luddatumbazo.odatnurd.net"
GITHUB_ROOT_URI = "https://github.com/OdatNurd/luddatumbazo"


################################################################################
# D E V   S E R V E R   S E T T I N G S
################################################################################

[dev]
ip = "localhost"
port = 3000
